name: release
on: 
    workflow_dispatch:
    push:
      tags:
        - 'v*'
permissions:
  contents: read
  actions: read
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--no-deprecation"
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run build
      - name: Upload artifact to GitHub Releases
        run: |
            version="v$(node -p "require('./package.json').version")"
            (cd ./dist/resources && sha256sum extension-trivy.tar) > extension-trivy_checksums.txt
            if gh release view $version; then
              gh release upload $version ./dist/resources/extension-trivy.tar ./extension-trivy_checksums.txt --clobber
            else
              gh release create --generate-notes $version ./dist/resources/extension-trivy.tar ./extension-trivy_checksums.txt
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
